### PR TITLE
Add new switch color options for 0.101.x

### PR DESCRIPTION
**Pull request by TheZoker**
Before (with 0.101.0b0):
Screenshot from 2019-10-24 16-34-49

After:
Screenshot from 2019-10-24 16-30-46

### CODE REVIEW

**Comment by pho3nixf1re** [comment]
Please attach some screenshots to the PR as examples. Bonus points if you could submit updated screenshots for the README.

**Comment by TheZoker** [comment]
I added the pictures. Actually nothing changes, there was just a change in parameter names:
https://github.com/home-assistant/home-assistant-polymer/pull/3683

We can also remove the old ones:
https://github.com/home-assistant/home-assistant-polymer/pull/4017/files

**Comment by maartenpaauw** [comment]
Thank you for submitting a pull request! About the README screenshots; I've created a little script which will make them automatically. I can make them this weekend.

About removing the old variables. If you want you can create a separated PR.

**Comment by maartenpaauw** [comment]
Screenshot tool: https://github.com/maartenpaauw/tiny-scripts/tree/master/theme-screenshot

I guess I have to add a README and default home assistant configuration soon! 😄

**Review by pho3nixf1re — APPROVED** [review]

**Pull request merged**
