### PR TITLE
Card background color variable has a new name

### LINKED ISSUE #18: paper-card-background-color is removed
Following the [beta release notes](https://rc.home-assistant.io/blog/2020/07/14/release-113/):
> The theme variable paper-card-background-color is removed. You can use ha-card-background or card-background-color as a replacement.
> In general, all variables that start with paper will be removed at some point.

https://github.com/home-assistant/frontend/pull/6377

### PR DESCRIPTION
**Pull request by pho3nixf1re**
The `paper-` prefixed theme variables are deprecated. In particular the
card background color is no longer working and must be renamed.

Closes #18

### CODE REVIEW

**Comment by TheZoker** [comment]
Can confirm, that this works!

**Comment by pho3nixf1re** [comment]
@maartenpaauw I do not have override permissions to merge this without your approval.

**Comment by maartenpaauw** [comment]
@pho3nixf1re what is your opinion about alphabetical sorted variables? 

Oh, by the way. I'll give you the permissions.

**Review by maartenpaauw — CHANGES_REQUESTED** [review]
I think variables are easier to find when the list is alphabetically sorted. What is your opinion?

**Comment by maartenpaauw** [comment]
@pho3nixf1re, I've given you the permissions. If the permission is not right, send me a message.

**Comment by pho3nixf1re** [comment]
Yes I do! Oversight on my part, updated.

**Review by maartenpaauw — APPROVED** [review]

**Pull request merged**
